/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "CyClock_1.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC_DelSig_1.h"
#include "Vin_aliases.h"
#include "Vin.h"
#include "UART_1.h"
#include "Timer_1.h"
#include "isr_Timer_1.h"
#include "SDA_1_aliases.h"
#include "SDA_1.h"
#include "SCL_1_aliases.h"
#include "SCL_1.h"
#include "Clock_1.h"
#include "RST_1_aliases.h"
#include "RST_1.h"
#include "I2C_1.h"
#include "I2C_1_PVT.h"
#include "SPIM_1.h"
#include "SPIM_1_PVT.h"
#include "Clock_2.h"
#include "sclk_aliases.h"
#include "sclk.h"
#include "ss_aliases.h"
#include "ss.h"
#include "miso_aliases.h"
#include "miso.h"
#include "ADC_DelSig_1_AMux.h"
#include "ADC_DelSig_1_Ext_CP_Clk.h"
#include "ADC_DelSig_1_IRQ.h"
#include "ADC_DelSig_1_theACLK.h"
#include "UART_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

